### ISSUE TITLE
how to add php block class & phtml file?

### ISSUE THREAD

**Issue by sivajik34** [sohelrana09/magento2-module-additional-shipping-block#1]
I'm new to knockout.js. here only html file is there.but how to write business logic.Can you give some idea?

**Comment by sohelrana09** [comment]
Hey

can you check 
https://github.com/magento/magento2-samples/tree/master/sample-module-webapi-client
module?

**Comment by sivajik34** [comment]
I think i need to do more r&d on knockout.js .I know about  block,layout,phtml concepts.Actually i need to add some text fields based on some logic.but here why they are doing this much of complexity(js,html files).Anyway once again  thanks for your response.
