### ISSUE TITLE
need to display text box field based on system configuration value? 

### ISSUE THREAD

**Issue by sivajik34** [sohelrana09/magento2-module-additional-shipping-block#2]
If you don't mind Please help me on following this.
I tried magento samples.still confused.
I have status (enable/disable) field in system configuration.
if status enabled need to display this field.
where I need to write this logic.how to pass this to html file.
Thanks in advance.

**Comment by sohelrana09** [comment]
Check last updated code.

**Comment by sivajik34** [comment]
Thank you.Please look at updated code
https://github.com/sivajik34/Delivery-Signature-Magento2

Actually i want to develop free extension for delivery signature.
requirement:
Customer can choose delivery signature for x amount.
Admin have this option to display based on status & minimum order amount.
I want you to contribute in your free time.
